# Qwen-Agent Configuration File
# Edit this file to customize your setup

# Model Configuration
models:
  # Main orchestrator model (handles agent logic, function calling, reasoning)
  orchestrator:
    name: "areebtechnology2025/Qwen3-30B-Areeb-Lora"
    url: "http://localhost:8000/v1"
    api_key: "EMPTY"
    temperature: 0.7
    top_p: 0.8
    max_tokens: 4096  # Reduced for faster responses
    max_input_tokens: 58000
    timeout: 150  # Increased to 2.5 minutes to wait for coder responses

  # Specialized code generation model (handles coding tasks)
  code_generator:
    name: "Qwen/Qwen2.5-Coder-32B-Instruct"
    url: "http://localhost:8001/v1/chat/completions"
    api_key: "EMPTY"
    temperature: 0.1  # Lower for consistent code generation
    top_p: 0.95
    max_tokens: 2048  # Reduced for faster responses
    timeout: 120  # Increased to 2 minutes for complex code generation

# Server Configuration
server:
  # API Server settings
  api:
    host: "0.0.0.0"
    port: 8002
    log_level: "info"
    cors_origins: ["*"]
    
  # GUI Server settings  
  gui:
    host: "0.0.0.0"
    port: 7860
    share: false
    auth: "api_key"  # Use API key authentication for usage tracking

# Agent Configuration
agent:
  # System message for the agent (optimized for speed)
  system_message: |
    You are an AI assistant with access to specialized coding tools.

    Tool Usage:
    - Use advanced_code_generator ONLY for explicit code requests: writing, modifying, creating scripts, refactoring
    - DO NOT use tools for conversations, greetings, or explanations
    - Use code_interpreter only for running/testing code
    - For programming questions, explain directly without tools

    Be helpful, clear, and concise in your responses.

  # Available tools for the agent
  tools:
    - "advanced_code_generator"
    - "code_interpreter"
    # Add more tools as needed:
    # - "web_search"
    # - "file_manager"
    # - "image_gen"

  # Default files to load (if any)
  default_files: []

# Authentication Configuration
authentication:
  enabled: true  # Enable authentication for security
  api_keys:
    # Example API key configuration
    "V2C-8UkDpfeuisiWxMCkf-5cFpY9zvRxy5MoZ47PVLY":
      name: "Continue/Roo Code"
      permissions: ["chat", "code_generation"]
      rate_limit: 100  # requests per hour
    # Add more API keys here as needed
    # "your-api-key-here":
    #   name: "User Name"
    #   permissions: ["chat", "code_generation"]
    #   rate_limit: 100
  default_permissions: ["chat"]

# Performance Configuration
performance:
  max_concurrent_requests: 10
  request_timeout: 300  # 5 minutes
  enable_caching: true
  cache_size: 100

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null  # Set to a file path to log to file
  
# Development Configuration
development:
  debug: false
  reload: false
  profiling: false 